#!/usr/bin/env python3

import os
import asyncio
from aiohttp import web
import aiohttp
from argparse import ArgumentParser

from claude.app import aio_app

os.environ['CLAUDE_DEBUG_MODE'] = '1'

parser = ArgumentParser()
parser.add_argument('-p', '--port', default = 5000)

args = parser.parse_args()

loop = asyncio.get_event_loop()
web.run_app(aio_app, port = args.port)
