#!/usr/bin/env python3

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-p', '--port', default = 5000)

args = parser.parse_args()

from claude.app import app

app.run(
    host = '0.0.0.0',
    port = args.port,
    debug = True,
)
